Importing Libraries

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

Data Preprocessing

Training Image Preprocessing

In [4]:
train=r"C:\Users\ASUS\plant_diseases_extracted\New Plant Diseases Dataset(Augmented)\New Plant Diseases Dataset(Augmented)\train"
training_set = tf.keras.utils.image_dataset_from_directory(
    train,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


Validation Image Preprocessing

In [5]:
valid=r"C:\Users\ASUS\plant_diseases_extracted\New Plant Diseases Dataset(Augmented)\New Plant Diseases Dataset(Augmented)\valid"
validation_set = tf.keras.utils.image_dataset_from_directory(
    valid,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [9]:
for x,y in training_set:
    print(x)
    print(y)
    print(x.shape)
    print(y.shape)
    break

tf.Tensor(
[[[[146.   136.   144.  ]
   [151.75 141.75 149.75]
   [151.75 141.75 149.75]
   ...
   [138.25 129.25 134.25]
   [148.   139.   144.  ]
   [149.25 140.25 145.25]]

  [[143.25 133.25 141.25]
   [147.75 137.75 145.75]
   [147.25 137.25 145.25]
   ...
   [151.   142.   147.  ]
   [143.75 134.75 139.75]
   [149.25 140.25 145.25]]

  [[157.5  147.5  155.5 ]
   [152.5  142.5  150.5 ]
   [148.75 138.75 146.75]
   ...
   [143.75 134.75 139.75]
   [157.5  148.5  153.5 ]
   [162.75 153.75 158.75]]

  ...

  [[136.5  123.5  132.5 ]
   [142.5  129.5  138.5 ]
   [144.5  131.5  140.5 ]
   ...
   [ 83.    69.    69.  ]
   [ 80.    66.    66.  ]
   [ 88.    74.    74.  ]]

  [[142.   129.   138.  ]
   [137.75 124.75 133.75]
   [132.   119.   128.  ]
   ...
   [ 87.75  71.75  72.75]
   [ 98.75  82.75  83.75]
   [ 97.    81.    82.  ]]

  [[138.   125.   134.  ]
   [133.25 120.25 129.25]
   [126.   113.   122.  ]
   ...
   [ 99.25  83.25  84.25]
   [ 98.5   82.5   83.5 ]
   [105.    89.    9

implementing the neural network

In [17]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D,Flatten
from tensorflow.keras.models import Sequential

In [14]:
model = Sequential()

In [18]:
model.add(Conv2D(filters=32, kernel_size=3, padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32, kernel_size=3, padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [19]:
model.add(Conv2D(filters=64, kernel_size=3, padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=64, kernel_size=3, padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [20]:
model.add(Conv2D(filters=128, kernel_size=3, padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=128, kernel_size=3, padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [21]:
model.add(Conv2D(filters=256, kernel_size=3, padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=256, kernel_size=3, padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [22]:
model.add(Flatten())

In [23]:
model.add(Dense(units=1024,activation='relu'))

In [24]:
model.add(Dense(units=38,activation='softmax'))

Compiling the model

In [25]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 128, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 128, 128, 32)      9248      
                                                                 
 conv2d_2 (Conv2D)           (None, 128, 128, 32)      9248      
                                                                 
 conv2d_3 (Conv2D)           (None, 128, 128, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 64, 64, 32)       0         
 )                                                               
                                                                 
 conv2d_4 (Conv2D)           (None, 64, 64, 64)        18496     
                                                        

Training the model

In [27]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 [==============================] - 986s 434ms/step - loss: 1.2225 - accuracy: 0.6399 - val_loss: 0.4838 - val_accuracy: 0.8388
Epoch 2/10
2197/2197 [==============================] - 506s 230ms/step - loss: 0.3369 - accuracy: 0.8889 - val_loss: 0.3289 - val_accuracy: 0.8941
Epoch 3/10
2197/2197 [==============================] - 459s 209ms/step - loss: 0.2318 - accuracy: 0.9227 - val_loss: 0.2412 - val_accuracy: 0.9243
Epoch 4/10
2197/2197 [==============================] - 533s 242ms/step - loss: 0.1864 - accuracy: 0.9374 - val_loss: 0.2989 - val_accuracy: 0.9067
Epoch 5/10
2197/2197 [==============================] - 454s 207ms/step - loss: 0.1459 - accuracy: 0.9517 - val_loss: 0.2651 - val_accuracy: 0.9219
Epoch 6/10
2197/2197 [==============================] - 450s 205ms/step - loss: 0.1421 - accuracy: 0.9526 - val_loss: 0.3429 - val_accuracy: 0.9034
Epoch 7/10
2197/2197 [==============================] - 460s 210ms/step - loss: 0.1234 - accuracy: 0.9597 - val_

Model Evaluation on Training set

In [28]:
train_loss,train_acc = model.evaluate(training_set)

2197/2197 [==============================] - 104s 47ms/step - loss: 0.0686 - accuracy: 0.9784


In [29]:
print(train_loss,train_acc)

0.06861492991447449 0.9783768653869629


Model Evaluation on Validation set

In [30]:
val_loss,val_acc=model.evaluate(validation_set)

550/550 [==============================] - 26s 46ms/step - loss: 0.3768 - accuracy: 0.9144


In [31]:
print(val_loss,val_acc)

0.3767746388912201 0.9143523573875427


Saving the model

In [32]:
model.save("trained_model.keras")

In [33]:
training_history.history

{'loss': [1.2224533557891846,
  0.3369305729866028,
  0.2318025827407837,
  0.18644899129867554,
  0.1459229737520218,
  0.1420845091342926,
  0.1233576312661171,
  0.1273830533027649,
  0.10935060679912567,
  0.12015735357999802],
 'accuracy': [0.6399317383766174,
  0.8889394402503967,
  0.9227114319801331,
  0.9374350905418396,
  0.9517035484313965,
  0.9526424407958984,
  0.9597126245498657,
  0.9584892392158508,
  0.9649335145950317,
  0.9619887471199036],
 'val_loss': [0.48381075263023376,
  0.32887372374534607,
  0.24121835827827454,
  0.29893428087234497,
  0.26511773467063904,
  0.3428776264190674,
  0.3264375329017639,
  0.3403274118900299,
  0.3293282389640808,
  0.3767743706703186],
 'val_accuracy': [0.8387776017189026,
  0.8941497802734375,
  0.9243113994598389,
  0.906726598739624,
  0.9219212532043457,
  0.903425931930542,
  0.9087184071540833,
  0.9116207361221313,
  0.9141247272491455,
  0.9143523573875427]}

In [34]:
#Recording History in Json
import json
with open("training_hist.json","w") as f:
    json.dump(training_history.history,f)

In [35]:
class_name = validation_set.class_names
class_name

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_

In [36]:
test_set = tf.keras.utils.image_dataset_from_directory(
    valid,
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [37]:
y_prediction = model.predict(test_set)
y_prediction

550/550 [==============================] - 25s 43ms/step


array([[1.0000000e+00, 1.6968899e-15, 2.5545182e-20, ..., 4.1649877e-35,
        2.0909863e-24, 9.4690580e-27],
       [9.6977746e-01, 2.0840378e-02, 2.8994049e-05, ..., 1.7230055e-07,
        2.7227182e-07, 1.5781328e-05],
       [1.0000000e+00, 2.8528006e-16, 1.2242012e-17, ..., 6.8473814e-30,
        5.5744933e-21, 2.3372086e-22],
       ...,
       [1.8684256e-08, 1.7147144e-15, 5.0763449e-10, ..., 7.7979465e-08,
        1.1846954e-12, 9.9462152e-01],
       [3.6251593e-13, 4.0347376e-23, 7.1196219e-15, ..., 3.0057117e-06,
        9.2924817e-20, 9.9999058e-01],
       [1.5758406e-16, 1.7263179e-16, 2.7276711e-18, ..., 3.7114097e-12,
        1.5976374e-08, 8.7161785e-01]], dtype=float32)